#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H


#define DIO_DIR_PIN_NO_0         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_1         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_2         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_3         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_4         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_5         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_6         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_7         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_8         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_9         DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_10        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_11        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_12        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_13        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_14        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_15        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_16        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_17        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_18        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_19        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_20        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_21        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_22        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_23        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_24        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_25        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_26        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_27        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_28        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_29        DIO_PIN_OUTPUT
#define DIO_DIR_PIN_NO_30        DIO_PIN_INPUT
#define DIO_DIR_PIN_NO_31        DIO_PIN_OUTPUT


#endif
